### ISSUE TITLE
Clear() does not compile

### ISSUE THREAD

**Issue by prr123** [dolthub/swiss#21]
I compiled the quickstart program and the compiler issued the error message m.Clear() 
"m.Clear undefined (type *swiss.Map[string, int] has no field or method Clear)"

In the github code, Clear() is a method. 

I don't really understand: the downloaded version must be different from the github current code.

**Comment by reltuk** [comment]
Thanks for your interest in swiss.

We had done a release since `Clear()` was added. I have just tagged `v0.2.0`, so you can `go get github.com/dolthub/swiss` and pick up the new version I think.

In the future, if there are unreleased changes in a go module repository's branch that you want to try out, you can go get a specific commit, like: `go get github.com/dolthub/swiss@df81ed48fd41110847784b75f76ed267f7091fb2`.

Thanks again! Closing for now, but feel free to reopen if you need anything further here.
